# Generated by Django 5.0.6 on 2024-06-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies_rates_api', '0002_alter_currencyrate_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyrate',
            name='rate',
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
    ]
